#------------------------------------------------------------------------
#                      多库分片自定义分库分表precise                        #
#------------------------------------------------------------------------

sharding:
  jdbc:
    config:
      sharding:
        binding-tables: t_order,t_user_info
        broadcast-tables: t_company
        default-data-source-name: ds-0  
        props:
          sql:
            show: true
        tables:
          t_order: 
            ##分库策略
            database-strategy:
              standard:
                ##分片键
                sharding-column: company_id
                precise-algorithm-class-name: com.sharding.demo.config.CompanyPreciseDBShardingAlgorithm
            ##分表策略
            key-generator-column-name: order_id  
            table-strategy:
              complex:
                sharding-columns: create_time,order_id
                algorithm-class-name: com.sharding.demo.config.OrderComplexShardingStrategy
          t_user_info: 
            database-strategy:
              standard:
                sharding-column: company_id
                precise-algorithm-class-name: com.sharding.demo.config.CompanyPreciseDBShardingAlgorithm
            actual-data-nodes: ds-$->{0..2}.t_user_info_$->{0..4}
            key-generator-column-name: user_id
            table-strategy:
              standard: 
                sharding-column: user_id
                precise-algorithm-class-name: com.sharding.demo.config.UserPreciseShardingAlgorithm
    datasource:
      names: ds-0,ds-1,ds-2
      ds-0: 
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://59.110.164.254:3306/ops_0?useSSL=false&useUnicode=true&characterEncoding=utf-8
        username: root
        password: root
        maximumPoolSize: 50
        connectionTestQuery: select 1
      ds-1: 
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://59.110.164.254:3306/ops_1?useSSL=false&useUnicode=true&characterEncoding=utf-8
        username: root
        password: root
        maximumPoolSize: 50
        connectionTestQuery: select 1  
      ds-2: 
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://59.110.164.254:3306/ops_2?useSSL=false&useUnicode=true&characterEncoding=utf-8
        username: root
        password: root
        maximumPoolSize: 50
        connectionTestQuery: select 1    

 

